const SUPABASE_URL='https://yihtsjscgwaaxyfkdlos.supabase.co';
// Uses the same public anon key configured by the rest of the Jsvidey site.
const PROJECT_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInJlZiI6InlpaHRzanNjZ3dhYXh5ZmtkbG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE1NzA4NzgsImV4cCI6MjEwNzE0Njg3OH0.7-sfZ2nwoy7iOzGGdx69cWRj2C_Bdhk39y7_CdNfrlo';
(()=>{
 const $=id=>document.getElementById(id); if(!window.supabase){alert('Supabase gagal dimuat. Periksa koneksi.');return}
 const db=window.supabase.createClient(SUPABASE_URL,PROJECT_ANON_KEY);let state=null,currentTab='overview',confirmAction=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(n)||0),money=n=>'Rp'+fmt(n),date=v=>v?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—',bytes=n=>!n?'—':n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;
 function toast(text,error=false){const el=$('toast');el.textContent=text;el.classList.toggle('error',error);el.hidden=false;window.setTimeout(()=>el.hidden=true,6000)}
 function runAction(action,payload={}){return db.rpc('jsvidey_admin_action',{action,payload})}
 function goto(tab){currentTab=tab;document.querySelectorAll('.admin-nav a[data-tab]').forEach(a=>a.classList.toggle('active',a.dataset.tab===tab));document.querySelectorAll('.admin-section').forEach(s=>s.classList.toggle('active',s.id===`section-${tab}`));const active=document.querySelector(`.admin-nav a[data-tab="${tab}"]`);$('pageTitle').textContent=active?active.textContent.trim().replace(/\s+—?\s*\d*$/,''):'Control Center';$('pageSubtitle').textContent=({overview:'Kontrol operasional platform dari satu tempat.',media:'Moderasi semua media yang tercatat.',withdrawals:'Review dan putuskan permintaan penarikan.',members:'Kelola akses dan akun member.',revenue:'Pengaturan CPM dan pendapatan tercatat.',ads:'Konfigurasi titik iklan di player.',storage:'Atur batas upload dan kuota aplikasi.',platform:'Pengaturan maintenance dan pengumuman.'})[tab]||'';location.hash=tab}
 document.querySelectorAll('.admin-nav a[data-tab]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();goto(a.dataset.tab)}));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>goto(b.dataset.jump)));
 function confirm(title,text,action){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmModal').hidden=false;confirmAction=action}
 $('cancelConfirm').onclick=()=>{$('confirmModal').hidden=true;confirmAction=null};$('acceptConfirm').onclick=async()=>{if(!confirmAction)return;const fn=confirmAction;confirmAction=null;$('confirmModal').hidden=true;await fn()};
 async function adminAuth(){const {data:{user},error}=await db.auth.getUser();if(error||!user){location.replace('login.html');return false}const {data,isError}=await db.rpc('jsvidey_is_admin');if(isError||data!==true){document.body.innerHTML=`<main style="font:16px sans-serif;color:#eef;background:#080c16;min-height:100vh;display:grid;place-items:center;padding:24px;text-align:center"><div><h1>Akses administrator ditolak</h1><p>Akun ini belum terdaftar di tabel public.jsvidey_admins.</p><a style="color:#b9a4ff" href="dashboard.html">Kembali ke dashboard</a></div></main>`;return false}$('adminIdentity').textContent=user.email||user.id;return true}
 async function load(){ $('refreshButton').disabled=true;$('systemStatus').textContent='Memuat data…';try{const {data,error}=await db.rpc('jsvidey_admin_dashboard');if(error)throw error;state=data;renderAll();$('systemStatus').textContent='Database terhubung';$('dbStatus').textContent='Terhubung';$('dbStatus').className='pill good'}catch(e){console.error(e);toast(e.message||'Gagal memuat data admin. Jalankan SQL migration admin.',true);$('systemStatus').textContent='Perlu konfigurasi';$('dbStatus').textContent='Error';$('dbStatus').className='pill bad'}finally{$('refreshButton').disabled=false}}
 function renderAll(){if(!state)return;const c=state.counts||{},cfg=state.config||{}; $('statUsers').textContent=fmt(c.users);$('statVideos').textContent=fmt(c.videos);$('statWithdrawals').textContent=fmt(c.pending_withdrawals);$('statRevenue').textContent=money(c.revenue);$('mediaCount').textContent=fmt(c.videos);$('withdrawCount').textContent=fmt(c.pending_withdrawals);$('revenueTotal').textContent=money(c.revenue);$('revenueViews').textContent=fmt(c.views);$('actualCpm').textContent=money(c.views?Number(c.revenue)*1000/Number(c.views):0);$('websiteStatus').textContent=cfg.maintenance_enabled?'Maintenance':'Online';$('websiteStatus').className='pill '+(cfg.maintenance_enabled?'warn':'good');$('b2Status').textContent=cfg.bucket_label||'Configured via Secrets';$('b2Status').className='pill '+(cfg.bucket_label?'good':'warn');$('adsStatus').textContent=cfg.ads_enabled?'Aktif':'Nonaktif';$('adsStatus').className='pill '+(cfg.ads_enabled?'good':'');$('storageBadge').textContent=`${cfg.max_upload_mb||20} MB / file`;
 $('defaultCpm').value=cfg.default_cpm_idr??10000;$('creatorShare').value=cfg.creator_share_percent??60;$('maxUploadMb').value=cfg.max_upload_mb??20;$('storageQuotaGb').value=cfg.storage_quota_gb??100;$('bucketLabel').value=cfg.bucket_label??'jsvidey-media';$('maintenanceEnabled').checked=!!cfg.maintenance_enabled;$('maintenanceMessage').value=cfg.maintenance_message||'';$('registrationEnabled').checked=cfg.registration_enabled!==false;$('adsEnabled').checked=!!cfg.ads_enabled;$('preRoll').value=cfg.pre_roll||'off';$('midRollSeconds').value=cfg.mid_roll_seconds??300;$('adTagUrl').value=cfg.ad_tag_url||'';renderMedia();renderMembers();renderWithdrawals();renderNotifications()}
 function renderMedia(){const q=($('mediaSearch').value||'').toLowerCase(),rows=(state?.videos||[]).filter(v=>`${v.title} ${v.username} ${v.email}`.toLowerCase().includes(q));$('mediaRows').innerHTML=rows.length?rows.map(v=>`<tr><td><div class="media-cell"><span class="mini-icon"><i class="fa-solid fa-file-video"></i></span><span class="cell-main"><strong title="${esc(v.title)}">${esc(v.title)}</strong><small>${esc(v.id.slice(0,8))}…</small></span></div></td><td>${esc(v.username||'—')}<br><small>${esc(v.email||'')}</small></td><td><span class="pill ${v.status==='published'?'good':v.status==='rejected'?'bad':'warn'}">${esc(v.status||'draft')}</span></td><td>${bytes(v.file_size_bytes)}</td><td>${date(v.created_at)}</td><td><div class="row-actions"><button class="small-button danger" data-delete-video="${esc(v.id)}"><i class="fa-solid fa-trash"></i> Hapus</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty-cell">Tidak ada media yang cocok.</td></tr>';document.querySelectorAll('[data-delete-video]').forEach(b=>b.onclick=()=>confirm('Hapus media ini?','Metadata video akan dihapus. Jika file tersimpan di B2, endpoint admin-delete-media akan mencoba menghapus objeknya juga.',()=>deleteVideo(b.dataset.deleteVideo)));}
 async function deleteVideo(id){try{const {data,error}=await db.functions.invoke('admin-delete-media',{body:{video_id:id}});if(error)throw error;if(data?.error)throw new Error(data.error);toast('Media dan objek B2 (jika ada) berhasil dihapus.');await load()}catch(e){toast(`Gagal menghapus media: ${e.message||'kesalahan server'}. Deploy Edge Function admin-delete-media dan periksa kredensial B2.`,true)}}
 function renderMembers(){const q=($('memberSearch').value||'').toLowerCase(),rows=(state?.users||[]).filter(u=>`${u.username} ${u.display_name} ${u.email} ${u.id}`.toLowerCase().includes(q));$('memberRows').innerHTML=rows.length?rows.map(u=>{const banned=!!u.banned_until&&new Date(u.banned_until)>new Date();return `<tr><td><div class="member-cell"><span class="mini-icon"><i class="fa-solid fa-user"></i></span><span class="cell-main"><strong>${esc(u.display_name||u.username||'Member')}</strong><small>@${esc(u.username||'unknown')} ${u.is_admin?'· Admin':''}</small></span></div></td><td>${esc(u.email||'—')}</td><td>${date(u.created_at)}</td><td><span class="pill ${u.is_admin?'good':banned?'bad':'good'}">${u.is_admin?'Admin':banned?'Banned':'Aktif'}</span></td><td><div class="row-actions">${u.is_admin?'<span class="pill">Protected</span>':banned?`<button class="small-button approve" data-unban="${u.id}">Unban</button>`:`<button class="small-button" data-ban="${u.id}">Ban</button>`}<button class="small-button danger" data-delete-user="${u.id}" ${u.is_admin?'disabled':''}>Hapus</button></div></td></tr>`}).join(''):'<tr><td colspan="5" class="empty-cell">Tidak ada member yang cocok.</td></tr>';document.querySelectorAll('[data-ban]').forEach(b=>b.onclick=()=>confirm('Ban member ini?','Member tidak akan bisa login sampai di-unban.',()=>userAction('ban_user',b.dataset.ban)));document.querySelectorAll('[data-unban]').forEach(b=>b.onclick=()=>userAction('unban_user',b.dataset.unban));document.querySelectorAll('[data-delete-user]').forEach(b=>b.onclick=()=>confirm('Hapus akun member permanen?','Tindakan ini tidak dapat dibatalkan. Data yang terkait dapat ikut terhapus sesuai aturan database.',()=>userAction('delete_user',b.dataset.deleteUser)));}
 async function userAction(action,id){const {error}=await runAction(action,{user_id:id});if(error){toast(error.message,true);return}toast(action==='delete_user'?'Akun member dihapus.':action==='ban_user'?'Member berhasil di-ban.':'Member berhasil di-unban.');await load()}
 function renderWithdrawals(){const filter=$('withdrawFilter').value,rows=(state?.withdrawals||[]).filter(w=>filter==='all'||w.status===filter);$('withdrawRows').innerHTML=rows.length?rows.map(w=>`<tr><td><div class="cell-main"><strong>${esc(w.username||'Member')}</strong><small>${esc(w.email||w.user_id)}</small></div></td><td><strong>${money(w.amount_idr)}</strong></td><td>${esc(w.payout_method||'manual')}<br><small>${esc(w.payout_details||'—')}</small></td><td>${date(w.created_at)}</td><td><span class="pill ${w.status==='approved'?'good':w.status==='rejected'?'bad':'warn'}">${esc(w.status)}</span></td><td>${w.status==='pending'?`<div class="row-actions"><button class="small-button approve" data-review="approved" data-id="${w.id}"><i class="fa-solid fa-check"></i> Approve</button><button class="small-button danger" data-review="rejected" data-id="${w.id}"><i class="fa-solid fa-xmark"></i> Reject</button></div>`:'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty-cell">Belum ada permintaan withdraw untuk filter ini.</td></tr>';document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>confirm(b.dataset.review==='approved'?'Approve withdraw?':'Reject withdraw?',b.dataset.review==='approved'?'Saldo tersedia member akan dikurangi sesuai jumlah penarikan. Pastikan pembayaran sudah diproses sesuai prosedur.':'Permintaan ditandai ditolak; saldo tidak akan dikurangi.',()=>reviewWithdrawal(b.dataset.id,b.dataset.review)));}
 async function reviewWithdrawal(id,decision){const note=decision==='rejected'?'Rejected by admin':'';const {error}=await runAction('review_withdrawal',{withdrawal_id:id,decision,admin_note:note});if(error){toast(error.message,true);return}toast(`Withdraw ${decision==='approved'?'di-approve':'ditolak'}.`);await load()}
 function renderNotifications(){const rows=state?.notifications||[];$('notificationHistory').innerHTML=rows.length?rows.map(n=>`<article class="notification-item"><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p><small>${n.target_user_id?'Target: '+esc(n.target_user_id):'Semua member'} · ${date(n.created_at)}</small></article>`).join(''):'<p class="loading-cell">Belum ada notifikasi.</p>'}
 async function saveConfig(config,success){const {error}=await runAction('save_config',config);if(error){toast(error.message,true);return false}toast(success);await load();return true}
 $('revenueForm').onsubmit=async e=>{e.preventDefault();await saveConfig({default_cpm_idr:Number($('defaultCpm').value),creator_share_percent:Number($('creatorShare').value)},'Pengaturan CPM dan bagi hasil tersimpan.')};
 $('storageForm').onsubmit=async e=>{e.preventDefault();await saveConfig({max_upload_mb:Number($('maxUploadMb').value),storage_quota_gb:Number($('storageQuotaGb').value),bucket_label:$('bucketLabel').value.trim()},'Pengaturan storage tersimpan. Deploy ulang Edge Function untuk menerapkan limit upload dinamis.')};
 $('platformForm').onsubmit=async e=>{e.preventDefault();await saveConfig({maintenance_enabled:$('maintenanceEnabled').checked,maintenance_message:$('maintenanceMessage').value.trim(),registration_enabled:$('registrationEnabled').checked},'Status platform tersimpan. Halaman publik harus membaca konfigurasi maintenance/registrasi agar efeknya terlihat.')};
 $('adsForm').onsubmit=async e=>{e.preventDefault();await saveConfig({ads_enabled:$('adsEnabled').checked,pre_roll:$('preRoll').value,mid_roll_seconds:Number($('midRollSeconds').value),ad_tag_url:$('adTagUrl').value.trim()},'Pengaturan ad slots tersimpan. Player perlu diintegrasikan untuk menampilkan iklan.')};
 $('notificationTarget').onchange=()=>{$('targetUserWrap').hidden=$('notificationTarget').value!=='specific'};
 $('notificationForm').onsubmit=async e=>{e.preventDefault();const target=$('notificationTarget').value==='specific'?$('targetUserId').value.trim():null;if($('notificationTarget').value==='specific'&&!target){toast('Masukkan User ID target.',true);return}const {error}=await runAction('send_notification',{title:$('notificationTitle').value.trim(),body:$('notificationBody').value.trim(),target_user_id:target});if(error){toast(error.message,true);return}$('notificationForm').reset();$('targetUserWrap').hidden=true;toast('Notifikasi berhasil disimpan. Pastikan UI member membaca tabel jsvidey_notifications.');await load()};
 $('adjustmentForm').onsubmit=async e=>{e.preventDefault();const {error}=await runAction('add_earning',{user_id:$('earningUserId').value.trim(),amount_idr:Number($('earningAmount').value),views:Number($('earningViews').value)});if(error){toast(error.message,true);return}$('adjustmentForm').reset();toast('Penyesuaian pendapatan tercatat dan saldo diperbarui.');await load()};
 $('deleteAllMedia').onclick=()=>confirm('Hapus SEMUA media?','Tindakan ini menghapus semua metadata media dan mencoba menghapus objek B2 satu per satu. Tindakan tidak dapat dibatalkan.',deleteAllMedia);
 async function deleteAllMedia(){const videos=[...(state?.videos||[])];let ok=0,failed=0;for(const v of videos){try{const {data,error}=await db.functions.invoke('admin-delete-media',{body:{video_id:v.id}});if(error||data?.error)throw error||new Error(data?.error);ok++}catch(e){failed++;console.error('delete media failed',v.id,e)}}toast(`Selesai: ${ok} media dihapus${failed?`, ${failed} gagal (periksa konfigurasi Edge Function/B2)`:''}.`,failed>0);await load()}
 $('mediaSearch').addEventListener('input',renderMedia);$('memberSearch').addEventListener('input',renderMembers);$('withdrawFilter').addEventListener('change',renderWithdrawals);$('refreshButton').onclick=load;$('logoutButton').onclick=async()=>{await db.auth.signOut();location.href='index.html'};
 (async()=>{const ok=await adminAuth();if(!ok)return;await load();const tab=location.hash.replace('#','');if(['overview','media','withdrawals','members','revenue','ads','storage','platform'].includes(tab))goto(tab)})().catch(e=>{console.error(e);toast('Gagal memulai panel admin.',true)});
})();
