// Client-side maintenance UX and member notification display. Server-side RLS/RPCs remain the security boundary.
(()=>{
 const URL='https://yihtsjscgwaaxyfkdlos.supabase.co';
 const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInJlZiI6InlpaHRzanNjZ3dhYXh5ZmtkbG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE1NzA4NzgsImV4cCI6MjEwNzE0Njg3OH0.7-sfZ2nwoy7iOzGGdx69cWRj2C_Bdhk39y7_CdNfrlo';
 if(document.body.dataset.page==='admin')return;
 function start(){if(!window.supabase)return;const db=window.supabase.createClient(URL,SUPABASE_KEY),path=location.pathname.split('/').pop();
  db.rpc('jsvidey_public_platform_status').then(({data,error})=>{if(error||!data)return;
   if(path==='register.html'&&data.registration_enabled===false){const gate=()=>{const form=document.getElementById('registerForm');if(form){form.querySelectorAll('input,button').forEach(el=>el.disabled=true);const msg=document.getElementById('registerMessage');if(msg)msg.textContent='Pendaftaran member baru sedang dinonaktifkan oleh administrator.'}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',gate);else gate()}
   if(data.maintenance_enabled){const root=document.createElement('div');root.id='platformMaintenanceOverlay';root.style.cssText='position:fixed;z-index:999999;inset:0;background:#080c16;color:#eef2ff;display:grid;place-items:center;padding:24px;text-align:center;font:15px system-ui,sans-serif';root.innerHTML='<div style="max-width:520px"><div style="font-size:44px;color:#9c85ff;margin-bottom:18px"><i class="fa-solid fa-screwdriver-wrench"></i></div><p style="letter-spacing:2px;color:#9c85ff;font-size:11px;font-weight:700">JSVIDEY MAINTENANCE</p><h1 style="font-size:28px;margin:12px 0">Platform sedang dipelihara</h1><p id="maintenanceCopy" style="color:#a6b2c8;line-height:1.7"></p><a href="admin.html" style="display:inline-block;color:#c4b5fd;margin-top:16px">Admin login</a></div>';root.querySelector('#maintenanceCopy').textContent=data.maintenance_message||'Kami sedang melakukan pemeliharaan.';document.body.appendChild(root)}
  }).catch(()=>{});
  const bell=document.getElementById('notificationPopover');if(bell){db.auth.getUser().then(async({data:{user}})=>{if(!user)return;const {data,error}=await db.from('jsvidey_notifications').select('id,title,body,created_at,target_user_id').or(`target_user_id.is.null,target_user_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(15);if(error||!data)return;const old=bell.querySelector('.notification-empty');if(old)old.remove();if(!data.length){const empty=document.createElement('div');empty.className='notification-empty';empty.textContent='Belum ada notifikasi';bell.appendChild(empty);return}data.forEach(n=>{const item=document.createElement('article');item.style.cssText='padding:10px 0;border-top:1px solid #273248;max-width:290px';const title=document.createElement('strong');title.style.cssText='display:block;font-size:12px;color:#edf2ff';title.textContent=n.title;const body=document.createElement('p');body.style.cssText='font-size:11px;line-height:1.5;color:#9eacc2;margin:5px 0';body.textContent=n.body;const date=document.createElement('small');date.style.cssText='font-size:9px;color:#718099';date.textContent=new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short'}).format(new Date(n.created_at));item.append(title,body,date);bell.appendChild(item)})}).catch(()=>{})}
 }
 if(window.supabase){start();return}const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=start;document.head.appendChild(script);
})();
