
-- Jsvidey Dashboard REAL DATABASE extension (safe to run after the auth schema)
-- Dashboard metrics come from database records, not hard-coded demo values.
alter table public.profiles add column if not exists plan text not null default 'Basic';
alter table public.profiles drop constraint if exists profiles_plan_check;
alter table public.profiles add constraint profiles_plan_check check (plan in ('Basic','Pro','Premium'));

create table if not exists public.videos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 180),
  video_url text,
  thumbnail_url text,
  status text not null default 'draft' check (status in ('draft','processing','published','private','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists videos_user_created_idx on public.videos(user_id, created_at desc);
alter table public.videos enable row level security;
drop policy if exists "Creators can view their own videos" on public.videos;
create policy "Creators can view their own videos" on public.videos for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Creators can add their own videos" on public.videos;
create policy "Creators can add their own videos" on public.videos for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Creators can update their own videos" on public.videos;
create policy "Creators can update their own videos" on public.videos for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Creators can delete their own videos" on public.videos;
create policy "Creators can delete their own videos" on public.videos for delete to authenticated using (auth.uid() = user_id);

create table if not exists public.video_views (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.videos(id) on delete cascade,
  creator_id uuid not null references auth.users(id) on delete cascade,
  viewer_id uuid references auth.users(id) on delete set null,
  views integer not null default 1 check (views > 0),
  viewed_at timestamptz not null default now()
);
create index if not exists video_views_creator_date_idx on public.video_views(creator_id, viewed_at desc);
create index if not exists video_views_video_idx on public.video_views(video_id);
alter table public.video_views enable row level security;
drop policy if exists "Creators can read their video view stats" on public.video_views;
create policy "Creators can read their video view stats" on public.video_views for select to authenticated using (auth.uid() = creator_id);

create table if not exists public.creator_earnings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id uuid references public.videos(id) on delete set null,
  amount_idr bigint not null default 0 check (amount_idr >= 0),
  views integer not null default 0 check (views >= 0),
  cpm_idr numeric(12,2) not null default 0 check (cpm_idr >= 0),
  source text not null default 'ad_revenue',
  created_at timestamptz not null default now()
);
create index if not exists creator_earnings_user_date_idx on public.creator_earnings(user_id, created_at desc);
alter table public.creator_earnings enable row level security;
drop policy if exists "Creators can read their own earnings" on public.creator_earnings;
create policy "Creators can read their own earnings" on public.creator_earnings for select to authenticated using (auth.uid() = user_id);

create table if not exists public.creator_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  available_balance_idr bigint not null default 0 check (available_balance_idr >= 0),
  pending_balance_idr bigint not null default 0 check (pending_balance_idr >= 0),
  updated_at timestamptz not null default now()
);
alter table public.creator_wallets enable row level security;
drop policy if exists "Creators can read their own wallet" on public.creator_wallets;
create policy "Creators can read their own wallet" on public.creator_wallets for select to authenticated using (auth.uid() = user_id);

create or replace function public.initialize_jsvidey_creator_records()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.creator_wallets(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_jsvidey_wallet_created on auth.users;
create trigger on_jsvidey_wallet_created after insert on auth.users
for each row execute procedure public.initialize_jsvidey_creator_records();

-- View used by the dashboard. RLS on video_views ensures a creator only sees their own view records.
create or replace view public.creator_video_views
with (security_invoker = true) as
select v.user_id as creator_id, vv.video_id, vv.viewed_at, vv.views
from public.video_views vv
join public.videos v on v.id = vv.video_id and v.user_id = vv.creator_id;

-- Public leaderboard aggregates only public profile names and creator totals.
-- SECURITY FIX: evaluate base-table privileges and RLS as the querying user.
-- Note: global leaderboard visibility depends on the SELECT/RLS policies of
-- profiles, video_views, and creator_earnings. Do not loosen those policies
-- merely to silence this lint warning.
create or replace view public.creator_leaderboard
with (security_invoker = true) as
select p.id as user_id, p.username, p.display_name,
       coalesce(vt.total_views,0)::bigint as total_views,
       coalesce(et.total_earned_idr,0)::bigint as total_earned_idr
from public.profiles p
left join (
  select creator_id, sum(views)::bigint as total_views
  from public.video_views where viewed_at >= date_trunc('day', now()) group by creator_id
) vt on vt.creator_id = p.id
left join (
  select user_id, sum(amount_idr)::bigint as total_earned_idr
  from public.creator_earnings where created_at >= date_trunc('day', now()) group by user_id
) et on et.user_id = p.id;

grant select on public.creator_video_views to authenticated;
grant select on public.creator_leaderboard to authenticated;
grant select, insert, update, delete on public.videos to authenticated;
grant select on public.video_views to authenticated;
grant select on public.creator_earnings to authenticated;
grant select on public.creator_wallets to authenticated;

-- Backfill a wallet for users who existed before this migration.
insert into public.creator_wallets(user_id)
select id from auth.users on conflict(user_id) do nothing;


-- Enable INSERT events for live dashboard view activity. Run as Supabase SQL editor owner.
do $$ begin
  alter publication supabase_realtime add table public.video_views;
exception when duplicate_object then null;
end $$;
